---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.23.1-bullseye

inputs:
  - name: dp-search-data-importer

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-search-data-importer/ci/scripts/build.sh
